INSERT INTO USERS ( USERNAME, FIRSTNAME, LASTNAME, BILLING_ADDR_STREET, BILLING_ADDR_CITY, BILLING_ADDR_STATE, BILLING_ADDR_ZIP, SHIPPING_ADDR_STREET, SHIPPING_ADDR_CITY, SHIPPING_ADDR_STATE, SHIPPING_ADDR_ZIP, CREDIT_CARD_NAME, CREDIT_CARD_NUMBER, CREDIT_CARD_EXPIRATION_DATE, PROFILE_NAME, PROFILE_NUMBER, PROFILE_JOIN_DATE) VALUES ( 'credmond', 'Conor', 'Redmond', '123 Main St', 'Seattle', 'WA', '12345', '120 Wall St', 'New York', 'NY', '56789', 'Conor Redmond', '1234567890123456', '2015-04-18' ,'doubleirish','23432',  '2010-04-18' );
INSERT INTO USERS ( USERNAME, FIRSTNAME, LASTNAME, BILLING_ADDR_STREET, BILLING_ADDR_CITY, BILLING_ADDR_STATE, BILLING_ADDR_ZIP, SHIPPING_ADDR_STREET, SHIPPING_ADDR_CITY, SHIPPING_ADDR_STATE, SHIPPING_ADDR_ZIP, CREDIT_CARD_NAME, CREDIT_CARD_NUMBER, CREDIT_CARD_EXPIRATION_DATE, PROFILE_NAME, PROFILE_NUMBER, PROFILE_JOIN_DATE) VALUES ( 'jsmith', 'John', 'Smith', '1 infinite way', 'San Fran', 'CA', '34356', '343 pine ave', 'Portlandia', 'OR', '23423', 'John Smith', '278362387782723', '2015-04-06','smithy','234231',  '2011-04-18' );
INSERT INTO USERS ( USERNAME, FIRSTNAME, LASTNAME, BILLING_ADDR_STREET, BILLING_ADDR_CITY, BILLING_ADDR_STATE, BILLING_ADDR_ZIP, SHIPPING_ADDR_STREET, SHIPPING_ADDR_CITY, SHIPPING_ADDR_STATE, SHIPPING_ADDR_ZIP, CREDIT_CARD_NAME, CREDIT_CARD_NUMBER, CREDIT_CARD_EXPIRATION_DATE, PROFILE_NAME, PROFILE_NUMBER, PROFILE_JOIN_DATE) VALUES ( 'aredmond', 'Ana', 'Redmond', '454 woodland view', 'Seattle', 'WA', '12345', '233 Wall St', 'New York', 'NY', '56789', 'Ana Redmond', '1234567890123456', '2018-04-18','droid','45664',  '2012-04-18' );
INSERT INTO USERS ( USERNAME, FIRSTNAME, LASTNAME, BILLING_ADDR_STREET, BILLING_ADDR_CITY, BILLING_ADDR_STATE, BILLING_ADDR_ZIP, SHIPPING_ADDR_STREET, SHIPPING_ADDR_CITY, SHIPPING_ADDR_STATE, SHIPPING_ADDR_ZIP, CREDIT_CARD_NAME, CREDIT_CARD_NUMBER, CREDIT_CARD_EXPIRATION_DATE, PROFILE_NAME, PROFILE_NUMBER, PROFILE_JOIN_DATE) VALUES ( 'wsmith', 'Will', 'Smith', '12 bioshock drive', 'San Fran', 'CA', '34356', '343 pine ave', 'Portlandia', 'OR', '23423', 'John Smith', '278362387782723', '2015-04-06','jazzer','4363',  '2013-04-18' );
INSERT INTO USERS ( USERNAME, FIRSTNAME, LASTNAME, BILLING_ADDR_STREET, BILLING_ADDR_CITY, BILLING_ADDR_STATE, BILLING_ADDR_ZIP, SHIPPING_ADDR_STREET, SHIPPING_ADDR_CITY, SHIPPING_ADDR_STATE, SHIPPING_ADDR_ZIP, CREDIT_CARD_NAME, CREDIT_CARD_NUMBER, CREDIT_CARD_EXPIRATION_DATE, PROFILE_NAME, PROFILE_NUMBER, PROFILE_JOIN_DATE) VALUES ( 'thumbson', 'Tom', 'Thumb', '23 Pike St', 'Seattle', 'WA', '12345', '544 Wall St', 'New York', 'NY', '56789', 'Conor Redmond', '1234567890123456', '2019-04-18','toodleloo','3345',  '2014-04-18' );
INSERT INTO USERS ( USERNAME, FIRSTNAME, LASTNAME, BILLING_ADDR_STREET, BILLING_ADDR_CITY, BILLING_ADDR_STATE, BILLING_ADDR_ZIP, SHIPPING_ADDR_STREET, SHIPPING_ADDR_CITY, SHIPPING_ADDR_STATE, SHIPPING_ADDR_ZIP, CREDIT_CARD_NAME, CREDIT_CARD_NUMBER, CREDIT_CARD_EXPIRATION_DATE, PROFILE_NAME, PROFILE_NUMBER, PROFILE_JOIN_DATE) VALUES ( 'ttime', 'Tiny', 'Tim', '15 pine st', 'San Fran', 'CA', '34356', '343 pine ave', 'Portlandia', 'OR', '23423', 'John Smith', '278362387782723', '2015-04-06','wingman','7474',  '2015-04-18' );
INSERT INTO USERS ( USERNAME, FIRSTNAME, LASTNAME, BILLING_ADDR_STREET, BILLING_ADDR_CITY, BILLING_ADDR_STATE, BILLING_ADDR_ZIP, SHIPPING_ADDR_STREET, SHIPPING_ADDR_CITY, SHIPPING_ADDR_STATE, SHIPPING_ADDR_ZIP, CREDIT_CARD_NAME, CREDIT_CARD_NUMBER, CREDIT_CARD_EXPIRATION_DATE, PROFILE_NAME, PROFILE_NUMBER, PROFILE_JOIN_DATE) VALUES ( 'jlow ', 'Jennny', 'Lowes', '67 University St', 'Seattle', 'WA', '12345', '201 Wall St', 'New York', 'NY', '56789', 'Conor Redmond', '1234567890123456', '2017-04-18','iceman','37756',  '2016-04-18' );
INSERT INTO USERS ( USERNAME, FIRSTNAME, LASTNAME, BILLING_ADDR_STREET, BILLING_ADDR_CITY, BILLING_ADDR_STATE, BILLING_ADDR_ZIP, SHIPPING_ADDR_STREET, SHIPPING_ADDR_CITY, SHIPPING_ADDR_STATE, SHIPPING_ADDR_ZIP, CREDIT_CARD_NAME, CREDIT_CARD_NUMBER, CREDIT_CARD_EXPIRATION_DATE, PROFILE_NAME, PROFILE_NUMBER, PROFILE_JOIN_DATE) VALUES ( 'jbob', 'Jim', 'Bob', '111 oak ave', 'San Fran', 'CA', '34356', '343 pine ave', 'Portlandia', 'OR', '23423', 'John Smith', '278362387782723', '2015-04-06','jojo','68',  '2017-04-18' );
INSERT INTO USERS ( USERNAME, FIRSTNAME, LASTNAME, BILLING_ADDR_STREET, BILLING_ADDR_CITY, BILLING_ADDR_STATE, BILLING_ADDR_ZIP, SHIPPING_ADDR_STREET, SHIPPING_ADDR_CITY, SHIPPING_ADDR_STATE, SHIPPING_ADDR_ZIP, CREDIT_CARD_NAME, CREDIT_CARD_NUMBER, CREDIT_CARD_EXPIRATION_DATE, PROFILE_NAME, PROFILE_NUMBER, PROFILE_JOIN_DATE) VALUES ( 'ztop', 'Zed', 'Top', '73 Maple St', 'Seattle', 'WA', '12345', '988 Wall St', 'New York', 'NY', '56789', 'Conor Redmond', '1234567890123456', '2015-04-18','irishred','8766',  '2018-04-18' );
INSERT INTO USERS ( USERNAME, FIRSTNAME, LASTNAME, BILLING_ADDR_STREET, BILLING_ADDR_CITY, BILLING_ADDR_STATE, BILLING_ADDR_ZIP, SHIPPING_ADDR_STREET, SHIPPING_ADDR_CITY, SHIPPING_ADDR_STATE, SHIPPING_ADDR_ZIP, CREDIT_CARD_NAME, CREDIT_CARD_NUMBER, CREDIT_CARD_EXPIRATION_DATE, PROFILE_NAME, PROFILE_NUMBER, PROFILE_JOIN_DATE) VALUES ( 'aarrdvark', 'Alvin', 'Aardvark', '876 grass lawns Ave', 'San Fran', 'CA', '34356', '343 pine ave', 'Portlandia', 'OR', '23423', 'John Smith', '278362387782723', '2015-04-06','johno','4677',  '2019-04-06' );
INSERT INTO USERS ( USERNAME, FIRSTNAME, LASTNAME, BILLING_ADDR_STREET, BILLING_ADDR_CITY, BILLING_ADDR_STATE, BILLING_ADDR_ZIP, SHIPPING_ADDR_STREET, SHIPPING_ADDR_CITY, SHIPPING_ADDR_STATE, SHIPPING_ADDR_ZIP, CREDIT_CARD_NAME, CREDIT_CARD_NUMBER, CREDIT_CARD_EXPIRATION_DATE, PROFILE_NAME, PROFILE_NUMBER, PROFILE_JOIN_DATE) VALUES ( 'sredmond', 'Sean', 'Redmond', '101 Ballybunion', 'Seattle', 'IR', '12345', '456 Ballybunion St', 'New York', 'NY', '56789', 'Sean Redmond', '1234567890123456', '2016-04-18','seano','9668',  '2015-04-18' );


INSERT INTO GENRE (  NAME ) values
 ('High Brow Literature'), ('Vampire-Romance'), ('Western'),
  ('Mystery'), ('Childrens'), ('Young Adult'),
  ('Biography'), ('Sci-Fi'), ('Historical'),
    ('Pot Boiler'), ('Political Thriller'), ('Comedy');
 ;


INSERT INTO STUDENT (USERNAME,   FIRSTNAME, LASTNAME,  DOB)
            values('credmond', 'Conor'  , 'Redmond', '1972-12-31');

INSERT INTO STUDENT (USERNAME,   FIRSTNAME, LASTNAME,  DOB )
             values('jsmith', 'John'  ,    'Smith',   '1990-01-31' );


INSERT INTO STUDENT (USERNAME,   FIRSTNAME, LASTNAME,  DOB )
              values('pdiddy', 'Puffy'  ,    'Combs',   '1980-07-04' );

INSERT INTO STUDENT (USERNAME,   FIRSTNAME, LASTNAME,  DOB )
            values('aredmond', 'Ana'  , 'Redmond', '1974-01-01');

INSERT INTO STUDENT (USERNAME,   FIRSTNAME, LASTNAME,  DOB)
            values('cfredmond', 'Charles'  , 'Redmond', '1973-12-31');


INSERT INTO COURSE (   CODE,      TITLE,  DESCRIPTION)
values (   'CP225',  'Java in Data Tier ',   'JPA , Ibatis, Yada yada yada');

INSERT INTO COURSE (   CODE,      TITLE,  DESCRIPTION)
           values (   'CP333',   'Java Web apps ',   'Servlets, JSP, Spring MVC');

INSERT INTO COURSE (   CODE,      TITLE,  DESCRIPTION)
           values (   'CP444',   'Distributed Java ',   'RMI, JAXB, JSON, AJAX');


INSERT INTO COURSE (   CODE,      TITLE,  DESCRIPTION)
           values (   'LIT101',     '19th Century French literature ',   'Victor Hugo');


INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID)
                     values(    1     ,     1    );

INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID)
                     values(    1     ,     2    );

INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID)
                     values(    1     ,     3    );

INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID)
                     values(    2     ,     1    );

INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID)
                     values(    2     ,     2    );

INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID)
                     values(    4     ,     1    );
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID)
                     values(    4     ,     3    );



INSERT INTO DIRECTOR (    FIRSTNAME, LASTNAME,  DOB)
            values( 'Conor'  , 'Redmond', '1972-12-31');

INSERT INTO DIRECTOR (   FIRSTNAME, LASTNAME,  DOB )
             values(  'John'  ,    'Smith',   '1990-01-31' );


INSERT INTO DIRECTOR (    FIRSTNAME, LASTNAME,  DOB )
              values(  'Puffy'  ,    'Combs',   '1980-07-04' );

INSERT INTO DIRECTOR (    FIRSTNAME, LASTNAME,  DOB )
            values( 'Ana'  , 'Redmond', '1974-01-01');


INSERT INTO BOARD (   SYMBOL,      COMPANY_NAME  )
           values (   'GOOG',      'Google' );

INSERT INTO BOARD (   SYMBOL,      COMPANY_NAME)
           values (   'APPL',   'Apple');

INSERT INTO BOARD (   SYMBOL,      COMPANY_NAME)
           values (   'M$ft',   'Microsoft');


INSERT INTO BOARD (   SYMBOL,      COMPANY_NAME)
           values (   'ATT',     'AT&T');


INSERT INTO DIRECTOR_BOARD (DIRECTOR_ID, BOARD_ID)
                     values(    1     ,     1      );
INSERT INTO DIRECTOR_BOARD (DIRECTOR_ID, BOARD_ID)
                     values(    1     ,     2     );

INSERT INTO DIRECTOR_BOARD (DIRECTOR_ID, BOARD_ID)
                     values(    1     ,     3     );

INSERT INTO DIRECTOR_BOARD (DIRECTOR_ID, BOARD_ID)
                     values(    2     ,     1    );

INSERT INTO DIRECTOR_BOARD (DIRECTOR_ID, BOARD_ID)
                     values(    2     ,     2   );

INSERT INTO DIRECTOR_BOARD (DIRECTOR_ID, BOARD_ID)
                     values(    4     ,     1    );
INSERT INTO DIRECTOR_BOARD (DIRECTOR_ID, BOARD_ID)
                     values(    4     ,     3   );






INSERT INTO EMPLOYEE (    FIRST_NAME, LAST_NAME)
            values( 'Conor'  , 'Redmond' );

INSERT INTO EMPLOYEE (   FIRST_NAME, LAST_NAME )
             values(  'John'  ,    'Smith'  );


INSERT INTO EMPLOYEE (    FIRST_NAME, LAST_NAME )
              values(  'Puffy'  ,    'Combs'  );

INSERT INTO EMPLOYEE (    FIRST_NAME, LAST_NAME )
            values( 'Ana'  , 'Redmond' );


INSERT INTO PROJECT (         PROJECT_NAME  )
           values (   'Big Dig' );

INSERT INTO PROJECT (         PROJECT_NAME)
           values (   'Apollo Moon Shot');

INSERT INTO PROJECT (         PROJECT_NAME)
           values (   'TPS Reporting');


INSERT INTO PROJECT (         PROJECT_NAME)
           values (   'Chunnel');


INSERT INTO EMPLOYEE_PROJECT (EMPLOYEE_ID, PROJECT_ID, IS_PROJECT_LEAD)
                     values(    1     ,     1     , true );
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEE_ID, PROJECT_ID )
                     values(    1     ,     2    );

INSERT INTO EMPLOYEE_PROJECT (EMPLOYEE_ID, PROJECT_ID)
                     values(    1     ,     3   );

INSERT INTO EMPLOYEE_PROJECT (EMPLOYEE_ID, PROJECT_ID)
                     values(    2     ,     1   );

INSERT INTO EMPLOYEE_PROJECT (EMPLOYEE_ID, PROJECT_ID, IS_PROJECT_LEAD)
                     values(    2     ,     2  , true);

INSERT INTO EMPLOYEE_PROJECT (EMPLOYEE_ID, PROJECT_ID)
                     values(    4     ,     1    );
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEE_ID, PROJECT_ID )
                     values(    4     ,     3    );

